name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  AZURE_WEBAPP_NAME: yc2201pydoc

jobs:
  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: neonchicken/cam-test:${{ github.sha }}

  deploy:
    name: Deploy to Azure web app
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: registry.hub.docker.com/neonchicken/cam-test:${{ github.sha }}
